### ISSUE TITLE
uninitialized constant SeamlessDatabasePool

### ISSUE THREAD

**Issue by mrinterweb** [bdurand/seamless_database_pool#10]
I keep getting this error when my rails app starts. 

```text
/home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/seamless_database_pool-1.0.12/lib/active_record/connection_adapters/seamless_database_pool_adapter.rb:16:in `seamless_database_pool_connection': uninitialized constant SeamlessDatabasePool (NameError)
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
	from /home/sean/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
	from /home/sean/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:308:in `clear_cache!'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activerecord-3.2.11/lib/active_record/railtie.rb:97:in `block (2 levels) in <class:Railtie>'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:418:in `_run__3502549632160588927__prepare__1120799005775289733__callbacks'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/sean/work/event_center/config/environment.rb:31:in `<top (required)>'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/application.rb:103:in `require'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/application.rb:103:in `require_environment!'
	from /home/sean/.rvm/gems/ruby-1.9.3-p327@event_center-v3/gems/railties-3.2.11/lib/rails/commands.rb:40:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

My database.yml looks like this:
```yml
development: &DEFAULT
  adapter: seamless_database_pool
  database: my_dev_database
  pool_adapter: postgresql
  username: something
  host: localhost
  password: asecretpassword
  master:
    port: 5432
  read_pool:
    - port: 5433
      pool_weight: 4
```

Am I doing something wrong or is this a bug?

**Comment by mrinterweb** [comment]
I no longer work with the codebase that was encountering this error. Closing issue.
