### ISSUE TITLE
undefined method `unsigned' for ActiveRecord::ConnectionAdapters::ColumnDefinition

### ISSUE THREAD

**Issue by wjordan** [bdurand/seamless_database_pool#28]
When using Rails 5.0 with the mysql adapter via seamless_database_pool, a standard `add_column` change migration fails with the following stack trace (running `bundle exec rake db:migrate --trace`):

```
undefined method `unsigned' for #<ActiveRecord::ConnectionAdapters::ColumnDefinition:0x0055b0ff865280>
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/schema_creation.rb:15:in `visit_ColumnDefinition'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:39:in `visit_AddColumnDefinition'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/schema_creation.rb:20:in `visit_AddColumnDefinition'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:26:in `block in visit_AlterTable'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:26:in `map'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:26:in `visit_AlterTable'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:549:in `add_column'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:845:in `block in method_missing'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:814:in `block in say_with_time'
[RUBY]/benchmark.rb:288:in `measure'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:814:in `say_with_time'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:834:in `method_missing'
[RAILS]/db/migrate/20160812010138_add_processed_at_to_workshops.rb:3:in `change'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:788:in `exec_migration'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
[RUBY]/benchmark.rb:288:in `measure'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:771:in `block in migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:770:in `migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:950:in `migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1281:in `ddl_transaction'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `each'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `migrate_without_lock'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `block in migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1298:in `with_advisory_lock'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `up'
[GEMS]/activerecord-5.0.0/lib/active_record/migration.rb:983:in `migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
[GEMS]/activerecord-5.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
[GEMS]/rake-11.2.2/lib/rake/task.rb:248:in `call'
[GEMS]/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
[GEMS]/rake-11.2.2/lib/rake/task.rb:243:in `each'
[GEMS]/rake-11.2.2/lib/rake/task.rb:243:in `execute'
[GEMS]/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[RUBY]/monitor.rb:211:in `mon_synchronize'
[GEMS]/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
[GEMS]/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
[GEMS]/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
[GEMS]/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[GEMS]/rake-11.2.2/lib/rake/application.rb:108:in `each'
[GEMS]/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
[GEMS]/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
[GEMS]/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
[GEMS]/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
[GEMS]/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
[GEMS]/rake-11.2.2/lib/rake/application.rb:77:in `run'
[GEMS]/rake-11.2.2/exe/rake:27:in `<top (required)>'
[GEM_PATH]/bin/rake:23:in `load'
[GEM_PATH]/bin/rake:23:in `<top (required)>'
[GEMS]/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
[GEMS]/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
[GEMS]/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
[GEMS]/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
[GEMS]/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[GEMS]/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[GEMS]/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
[GEMS]/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
[GEMS]/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
[GEMS]/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
[GEMS]/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
[GEMS]/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
[GEM_PATH]/bin/bundle:23:in `load'
[GEM_PATH]/bin/bundle:23:in `<main>'
```

I tracked the issue down to the `create_table_definition` private method in the MySql2 connection adapter not being proxied properly, so the generic `ActiveRecord::ConnectionAdapters::TableDefinition` object is being passed around instead of the (required) `ActiveRecord::ConnectionAdapters::MySQL::TableDefinition`.

To work around this issue temporarily, I added the line:

```
            master_methods.concat(connection_class.private_instance_methods(false))
```

to [`seamless_database_pool_adapter.rb:101`](https://github.com/bdurand/seamless_database_pool/blob/master/lib/active_record/connection_adapters/seamless_database_pool_adapter.rb#L101), then the migration completed properly.

**Comment by wjordan** [comment]
fixed by #23.
