### ISSUE TITLE
Database connection from a non Rails application

### ISSUE THREAD

**Issue by fabiomassimo** [bdurand/seamless_database_pool#34]
I'm using a non this gem in a ruby application (no Rails) and I couldn't find the right way to connect to my database manually without Rails doing it for me under the hood.

The database.yml looks something like this

```yaml
development:
  adapter: seamless_database_pool
  database: my_database
  username: my_usernmae
  password: my_password
  pool_adapter: postgresql
  port: 5432
  master:
    host: master_ip
    pool_weight: 0
  read_pool:
    - host: slave_ip
```

and I'm trying to connect by using the following command

```ruby
  def self.connect_db!
    yaml = YAML.load(open(File.join(File.dirname(__FILE__),'../../db/config.yml')))
    config = OpenStruct.new(yaml[ENV["RACK_ENV"]])

    ActiveRecord::Base.establish_connection(
        :adapter => config[:adapter],
        :host => config[:host],
        :database => config[:database],
        :username => config[:username],
        :password => config[:password],
        :port => config[:port]
    )
  end
```

Although when I'm trying to run a query from my active record model I get a crash with following stack trace:

```
NoMethodError: undefined method `to_hash' for nil:NilClass
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/hash_with_indifferent_access.rb:131:in `update'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/hash_with_indifferent_access.rb:199:in `merge'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/seamless_database_pool-1.0.18/lib/active_record/connection_adapters/seamless_database_pool_adapter.rb:13:in `seamless_database_pool_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/attributes.rb:93:in `columns'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/attributes.rb:98:in `columns_hash'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:73:in `descends_from_active_record?'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:79:in `finder_needs_type_condition?'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/core.rb:256:in `relation'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/scoping/named.rb:33:in `default_scoped'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/scoping/named.rb:28:in `all'
/home/my-app/scheduler/shared/bundle/ruby/2.0.0/gems/activerecord-4.2.4/lib/active_record/querying.rb:10:in `where'
```

What am I doing wrong?

**Comment by fabiomassimo** [comment]
Found it!

I should have specified `pool_adapter` instead of the `adapter` when calling `ActiveRecord::Base.establish_connection`.
